# Generated by Django 3.2.8 on 2021-10-06 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='genres',
            options={'ordering': ['title'], 'verbose_name': 'Género', 'verbose_name_plural': 'Géneros'},
        ),
        migrations.RemoveField(
            model_name='genres',
            name='movie_id',
        ),
        migrations.AddField(
            model_name='movie',
            name='genres_id',
            field=models.ManyToManyField(to='movie.Genres', verbose_name='Película(s)'),
        ),
    ]
